### ISSUE TITLE
Segfault encountered during merge in Snowflake

### ISSUE THREAD

**Issue by LukeMckim** [PeerDB-io/peerdb#2312]
running into this error in latest version `stable-v0.19.1`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x362034f]

goroutine 2871425 [running]:
github.com/PeerDB-io/peer-flow/connectors/snowflake.(*mergeStmtGenerator).generateMergeStmt(0xc0264362d0, {0xc045d8331c, 0xe})
        /root/flow/connectors/snowflake/merge_stmt_generator.go:31 +0xaf
github.com/PeerDB-io/peer-flow/connectors/snowflake.(*SnowflakeConnector).mergeTablesForBatch.func1()
        /root/flow/connectors/snowflake/snowflake.go:560 +0x71
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.9.0/errgroup/errgroup.go:78 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2867236
        /go/pkg/mod/golang.org/x/sync@v0.9.0/errgroup/errgroup.go:75 +0x96
```

**Comment by serprex** [comment]
`nil` dereference is from `columns := normalizedTableSchema.Columns`. So `m.tableSchemaMapping[dstTable]` was missing
